#!/bin/bash

# output left our right from laptop
where=$1
shift

screens=`xrandr | grep ' connected'| awk '{print $1}'`
var=$(echo $screens|awk -F' ' '{print $1,$2,$3}')
set -- $var

if [[ $where =~ r.* ]]
	then where="--right-of"
	else
		where="--left-of"
fi

if [ -n "$3" ]
	then xrandr --output $1 --auto --output $2 --auto $where $1 --output $3 --auto $where $2
	exit
fi

if [ -n "$2" ]
	then xrandr --output $1 --auto --output $2 --auto $where $1
	exit
fi

xrandr --auto
exit

#$ xrandr --output SCREEN1 --auto --output SCREEN2 --auto --right-of SCREEN1
